version: '3.8'

services:
  web:
    build: ./super-drf
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./super-drf:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=laxz
      - POSTGRES_PASSWORD=laxz
      - POSTGRES_DB=dj_api_db

    ports:
      - 5432:5432

volumes:
  postgres_data: