version: "3.8"

networks:
  default:
    name: nginx-proxy-network
    external: true


services:
  web:
    build:
      context: ./super-drf
      dockerfile: Dockerfile.with-compose.prod
    command: gunicorn superduperdrf.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.staging
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.staging.db
      - ./.env.proxy
    expose:
      - 5432

  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      # args:
        # IDENTIFIER: "${IDENTIFIER}"
    volumes:
      - static_volume:/home/app/web/staticfiles
      - ./mediafiles:/home/app/web/mediafiles
      - ./logs:/home/app/web/logs
    env_file:
      - ./.env.proxy
    expose:
      - 80
      # - 8080 # if nginx stub
    depends_on:
      - web

volumes:
  static_volume:
